### PR TITLE
"SyntaxError: Unexpected token T" bugfix 

### PR DESCRIPTION
**Pull request by ader1990**
When "account import <file>" is executed,  "JSON.parse(stdout)" fails with "SyntaxError: Unexpected token T" error message.

### CODE REVIEW

**Comment by glennblock** [comment]
What version of node are you using?

-----Original Message-----

**Comment by ader1990** [comment]
node --version
v0.8.22

**Comment by glennblock** [comment]
K great! Thanks for the fixz

-----Original Message-----

**Comment by glennblock** [comment]
Thanks a ton!

**Comment by glennblock** [comment]
@ader1990 being that you used it, I'd like to know your experience so far / what you are using it for. If you feel so inclined, shoot me an email at glenn.block@gmail.com

**Pull request merged**
